export const OUTPUT_REPORT_SHEETS = {
  readMe: "Read Me",
  equipment: "Equipment Log",
  safety: "Safety Log",
  measuringPoints: "Measuring Points Log",
  meterCounters: "Meter Counters Log",
  shift: "Shift Log",
  kaizen: "Kaizen Log",
  master: "Master Log",
  kpiDashboard: "KPI Dashboard",
} as const;

export const EQUIPMENT_LOG_COLUMNS = [
  "Log ID",
  "Reported Date",
  "Reported Time",
  "Title",
  "Equipment ID",
  "Equipment Name",
  "Section",
  "Sub Location",
  "Equipment Category",
  "Criticality",
  "Issue Category",
  "Equipment Function",
  "Failure Mode",
  "Maintenance Type",
  "Root Cause",
  "Action Taken",
  "Spare Part/Consumable Ref",
  "Issue Status",
  "Severity",
  "Production Impact",
  "Downtime Hours",
  "Attachments Count",
  "Reported By",
  "Repeat Failure Flag",
  "Days Since Last Failure (same Equipment)",
] as const;

export const SAFETY_LOG_COLUMNS = [
  "Log ID",
  "Reported Date",
  "Reported Time",
  "Title",
  "Incident Category",
  "Section",
  "Location",
  "Incident Type",
  "Action Taken",
  "Issue Status",
  "Severity",
  "Requires PPE",
  "PPE Type",
  "Reportable (Factories Act)",
  "Immediate Action Required",
  "Attachments Count",
  "Reported By",
  "Days Open (if not Resolved)",
] as const;

export const MEASURING_POINTS_LOG_COLUMNS = [
  "Log ID",
  "Reported Date",
  "Reported Time",
  "Title",
  "Point ID",
  "Equipment ID",
  "Equipment Name",
  "Section",
  "Measurement Name",
  "Measurement UoM",
  "Measured Value",
  "Target Value",
  "Lower Limit",
  "Upper Limit",
  "Severity",
  "Attachments Count",
  "Reported By",
  "Out of Limit Flag",
  "Deviation % (vs Target)",
] as const;

export const METER_COUNTERS_LOG_COLUMNS = [
  "Log ID",
  "Reported Date",
  "Reported Time",
  "Title",
  "Counter ID",
  "Equipment ID",
  "Location",
  "Counter Name",
  "Meter Type",
  "Counter UoM",
  "Previous Reading",
  "Current Reading",
  "Expected Consumption (for period)",
  "Days Since Last Reading",
  "Attachments Count",
  "Reported By",
  "Consumption Delta",
  "Deviation % (vs Expected)",
  "Deviation Flag",
] as const;

export const SHIFT_LOG_COLUMNS = [
  "Log ID",
  "Reported Date",
  "Reported Time",
  "Shift",
  "Title",
  "Description",
  "Equipment ID",
  "Location",
  "Issue Status",
  "Severity",
  "Spare Part/Consumables Ref",
  "Time Duration Hours",
  "Downtime Hours",
  "Attachments Count",
  "Reported By",
] as const;

export const KAIZEN_LOG_COLUMNS = [
  "Log ID",
  "Reported Date",
  "Reported Time",
  "Title",
  "Description",
  "Kaizen Category",
  "Department",
  "Location",
  "Expected Benefit",
  "Status",
  "Attachments Count",
  "Reported By",
  "Days Open",
] as const;

export const MASTER_LOG_COLUMNS = [
  "Log Type",
  "Log ID",
  "Reported Date",
  "Reported Time",
  "Month",
  "Section/Department",
  "Location",
  "Equipment ID",
  "Category/Type",
  "Severity",
  "Status",
  "Downtime Hours",
  "Reported By",
] as const;
