export const MODULE_TYPES = {
  EQUIPMENT_LOG: "EQUIPMENT_LOG",
  SAFETY_LOG: "SAFETY_LOG",
  MEASUREMENT_POINT: "MEASUREMENT_POINT",
  METER_COUNTER: "METER_COUNTER",
  SHIFT: "SHIFT",
  SUGGESTION: "SUGGESTION",
} as const;

export const MODULE_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  COMING_SOON: "COMING_SOON",
} as const;
