export const COMPANY_STATUS = {
  DEMO: "DEMO",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
  EXPIRED: "EXPIRED",
} as const;

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
} as const;

export const LOG_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  PLANNED: "PLANNED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  NEEDS_CORRECTION: "NEEDS_CORRECTION",
} as const;
