export const NOTIFICATION_TYPES = {
  SCHEDULE_ASSIGNED: "SCHEDULE_ASSIGNED",
  SCHEDULE_UPDATED: "SCHEDULE_UPDATED",
  SCHEDULE_CANCELLED: "SCHEDULE_CANCELLED",
  ADMIN_ANNOUNCEMENT: "ADMIN_ANNOUNCEMENT",
} as const;
